#!/bin/bash

eval set -- $(getopt -s bash \
	--options "c:a" \
	--longoptions "create:" \
	--name "fabrico" -- "$@")


# create <project name>
function create {
	project=$1
	fabricoroot=$(dirname $0)

	if [ -d "$project" ]; then
		# check if we're overwriting anything
		echo "project $project already exists!"
		exit 0
	else
		# create project directory and copy template
		echo "creating new fabrico project: $project"
		cp -r "./$fabricoroot/template/" "$project/"
		echo "template files copies successfully"
	fi
}


while true; do
	case $1 in
		-a)
			shift
			php src/Fabrico.cli.php
			;;

		-c|--create)
			shift
			create $1
			;;

		--)
			shift
			break
			;;
		
		*)
			shift
			break
			;;
	esac
	shift
done
