project: Propositum

loading:
  root: /
  core: ../..
  log: .log
  conf: .yml
  suffix: .php
  prefix: ../../../
  internal: /Fabrico
  httproot: /var/www/Dropbox/apache

directory:
  templates: /templates/
  controllers: /controllers/
  models: /models/
  views: /views/
  elements: /elements/
  configuration: /configuration/
  resource: /resources/resource/
  javascript: /resources/javascript/
  css: /resources/css/
  image: /resources/image/
  routing: /routing/
  include: /include/
  logs: /internals/logs/
  build: /internals/build
  dependency: /src/deps/

configuration:
  database: database/database
  routing: routing/routing

convention:
  controller_suffix: Controller
  controller_default: StandardController
  controller_default_file: standard
  configuration_default: configuration
  index_file: index
