<?php

$random = rand();
$classbase = 'autocomplete';
$id = "{$name}_{$random}";

$idfield = html::el('input', array(
	'type' => 'hidden',
	'name' => $name,
	'id' => "{$id}_id"
));

$valfield = html::el('input', array(
	'type' => 'text',
	'name' => "{$name}_text",
	'id' => $id,
	'class' => "{$classbase}input"
));

$results = html::el('div', array(
	'id' => "{$id}_results",
	'class' => "{$classbase}results"
));

$button = html::el('div', array(
	'class' => "{$classbase}runsearch"
));

$holder = html::el('div', array(
	'content' => $idfield . $valfield . $results . $button
));

$force = util::bool2string($force);
$css = cssfile(corefile('search.css'));
$comment = '/* generated by: data\search */';
$javascript = "Fabrico.ui.autocomplete('#{$id}', '{$method}', {$force});";
FabricoPageResource::onready($comment . PHP_EOL . $javascript);
echo $css . $holder;
