name: profiler
human_name: Profiler
description: Script profiler
tags:
  - debugging
  - profiler
  - profiling

env:
  - source: profiler_check.php
    required: true
    messages:
      pass: Profiler was found
      fail: No profiler was found

source:
  - name: profiler.php
    type: bootstrap

config:
  label: Project Profiler
  mode: 1
  output:
    class: util\profile\reports\Chart
    settings: []
