namespace: %Namespace%
bootstrap: []

handlers:
  config:
    Fabrico\Response\Handler\Http\InvalidRequestHandler:
      file: 404

  http:
    - Fabrico\Response\Handler\Http\ViewFileHandler
    - Fabrico\Response\Handler\Http\ControllerActionHandler
    - Fabrico\Response\Handler\Http\InvalidRequestHandler
