name: twig
human_name: Twig
description: Twig is a modern template engine for PHP

env:
  - source: twig_check.php
    required: true
    messages:
      pass: Twig found
      fail: Twig was not found

tags:
  - view
  - template
  - twig

source:
  - name: twig.php
    type: listener

config:
  extension: .twig
