#!/usr/bin/php
<?php

namespace Fabrico\Runtime\Setup\Cli;

use Fabrico\Command\Command;
use Symfony\Component\Console\Application;

$app = require 'scripts/app.php';
$conf = $app->getConfiguration();
$console = new Application();

foreach ($conf->get('app:commands') as $name => $clazz) {
    $command = new $clazz;

    if ($command instanceof Command) {
        $command->setConfiguration($conf);
    }

    $command->setName($name);
    $console->add($command);
}

$console->run();

